name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    
    strategy:
      matrix:
        destination: 
          - 'platform=iOS Simulator,name=iPhone 15,OS=17.0'
          - 'platform=macOS'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    
    - name: Install XcodeGen
      run: |
        brew install xcodegen
    
    - name: Generate Xcode Project
      run: |
        xcodegen generate
    
    - name: Build
      run: |
        xcodebuild -project bitchat.xcodeproj \
                   -scheme bitchat \
                   -destination '${{ matrix.destination }}' \
                   build
    
    - name: Test
      run: |
        xcodebuild -project bitchat.xcodeproj \
                   -scheme bitchat \
                   -destination '${{ matrix.destination }}' \
                   test
      continue-on-error: true
    
    - name: Archive iOS
      if: matrix.destination == 'platform=iOS Simulator,name=iPhone 15,OS=17.0'
      run: |
        xcodebuild -project bitchat.xcodeproj \
                   -scheme bitchat \
                   -destination 'generic/platform=iOS' \
                   -archivePath bitchat-ios.xcarchive \
                   archive
      continue-on-error: true
    
    - name: Archive macOS
      if: matrix.destination == 'platform=macOS'
      run: |
        xcodebuild -project bitchat.xcodeproj \
                   -scheme bitchat \
                   -destination 'generic/platform=macOS' \
                   -archivePath bitchat-macos.xcarchive \
                   archive
      continue-on-error: true

  lint:
    name: SwiftLint
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: |
        brew install swiftlint
    
    - name: Run SwiftLint
      run: |
        swiftlint lint --reporter github-actions-logging
      continue-on-error: true

  security-scan:
    name: Security Scan
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: >-
          p/security-audit
          p/secrets
          p/swift
      continue-on-error: true
